# Generated by Django 2.2.5 on 2019-09-25 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_hunter'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='body',
            field=models.TextField(default='', max_length=500),
        ),
    ]
